### Send otp to email for signup
POST http://localhost:3000/GoEvent/post/send-otp HTTP/1.1
Content-Type: application/json

{
    "email": "kaushal21092003kumar@gmail.com",
    "tag": "signup"
}


### Create a New User
POST http://localhost:3000/GoEvent/post/create-user HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "kaushal21092003kumar@gmail.com",
    "password": "okokokok",
    "organisation": "Test Organisation",
    "phone": "1234567890",
    "otp": "599377"
}


### Send otp to email for login
POST http://localhost:3000/GoEvent/post/send-otp HTTP/1.1
Content-Type: application/json

{
    "email": "kaushal21092003kumar@gmail.com",
    "tag": "login"
}


### Set user Login
POST http://localhost:3000/GoEvent/post/set-user HTTP/1.1
Content-Type: application/json

{
    "email": "kaushal21092003kumar@gmail.com",
    "password": "okokokok",
    "otp": "180924"
}
